apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr8-chatbot-llama
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr8-chatbot-llama
  name: apr8-chatbot-llama
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: apr8-chatbot-llama
